# Generated by Django 4.0.4 on 2022-09-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=70)),
                ('temperature', models.CharField(max_length=70)),
                ('pressure', models.CharField(max_length=70)),
                ('humidity', models.CharField(max_length=70)),
            ],
        ),
    ]
